server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10  
  retry:
    instances:
      foo-bar-att:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
      default:
        max-attempts: 5
spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password: root
  sleuth:
    sampler:
      probability: 1.0
#springdoc:
  #show-actuator: true
  #api-docs:
    #path: book-service/v3/api-docs
  #swagger-ui:
    #config-url: /book-service/v3/api-docs/swagger-config
    #url: /book-service/v3/api-docs
